(function (t) {
// en
t.add("clp_text.body", " Find your dream property whether it\u2019s a house, Apartment, Condo or Land with the #1 real estate property finder in the", "messages_js", "en");
t.add("clp_text.description", null, "messages_js", "en");
t.add("clp_text.search", "Search for", "messages_js", "en");
t.add("device_detection.cancel", "Dismiss message and stay on current page", "messages_js", "en");
t.add("device_detection.confirm", "Yes", "messages_js", "en");
t.add("device_detection.message_desktop", "We\u2019ve noticed that you are on a desktop device. Would you like to switch to our website\u2019s desktop version ?", "messages_js", "en");
t.add("device_detection.message_mobile", "We've noticed that you are on a mobile device. Would you like to switch to our mobile version ?", "messages_js", "en");
t.add("fb.instant_notification_title", "Instant Notifications (New)", "messages_js", "en");
t.add("fb.manage_save_search", "Manage Save Search on your profile.", "messages_js", "en");
t.add("form.contact.email_address.format_error_message", "Invalid email format.", "messages_js", "en");
t.add("form.contact.email_address.label", "Email", "messages_js", "en");
t.add("form.contact.email_address.label_required", "Email*", "messages_js", "en");
t.add("form.contact.first_name.invalid_format", "Invalid First Name Format", "messages_js", "en");
t.add("form.contact.first_name.label", "First Name", "messages_js", "en");
t.add("form.contact.first_name.required_error_message", "First name is required.", "messages_js", "en");
t.add("form.contact.last_name.invalid_format", "Invalid Surname Format", "messages_js", "en");
t.add("form.contact.last_name.label", "Surname", "messages_js", "en");
t.add("form.contact.last_name.required_error_message", "Surname is required.", "messages_js", "en");
t.add("form.contact.phone.format_error_message", "Invalid phone format.", "messages_js", "en");
t.add("form.contact.phone.label", "Phone Number", "messages_js", "en");
t.add("form.contact.phone.label_required", "Phone Number", "messages_js", "en");
t.add("form.contact.sub_title", "Please enter your contact information to help\nthe agent respond to you quickly.", "messages_js", "en");
t.add("form.contact.submit.mobile_label_pdp", "Send", "messages_js", "en");
t.add("form.contact.success_message", "We just sent your contact enquiry, you will be contacted soon.", "messages_js", "en");
t.add("form.contact.success_message2", "Your contact information has been sent!", "messages_js", "en");
t.add("form.contact.success_title", "Thank you for your request!", "messages_js", "en");
t.add("form.contact.title_pdp", "Ask about the property", "messages_js", "en");
t.add("form.contact.title_pdp_tablet", "Contact agent", "messages_js", "en");
t.add("search_bar.buy", "Buy", "messages_js", "en");
t.add("search_bar.for-rent", "for rent", "messages_js", "en");
t.add("search_bar.for-sale", "for sale", "messages_js", "en");
t.add("search_bar.newdevelopment", "New Development", "messages_js", "en");
t.add("search_bar.projects", "Projects", "messages_js", "en");
t.add("search_bar.rent", "Rent", "messages_js", "en");
t.add("search_bar.sale", "for sale", "messages_js", "en");
t.add("text.InCLP_callOut", "Refine the criteria of properties you are looking for", "messages_js", "en");
t.add("text.accept_saved_search", "By clicking, you accept our Terms & Conditions", "messages_js", "en");
t.add("text.alert_saved_message", "You have successfully created an email alert for your search criteria", "messages_js", "en");
t.add("text.alert_terms_and_conditions", "By\u00a0clicking\u00a0submit,\u00a0you\u00a0are\u00a0accepting\u00a0Lamudi's\u00a0%linkSplit%\u00a0Terms\u00a0and\u00a0Condition\u00a0%linkSplit%and\u00a0%linkSplit%\u00a0Privacy\u00a0Policy\u00a0%linkSplit%\u00a0page.", "messages_js", "en");
t.add("text.alerts_create_alert", "Create Alert", "messages_js", "en");
t.add("text.alerts_success", "Success", "messages_js", "en");
t.add("text.all", "All", "messages_js", "en");
t.add("text.amenities", "Amenities", "messages_js", "en");
t.add("text.any_price", "Any Price", "messages_js", "en");
t.add("text.any_size", "Any Size", "messages_js", "en");
t.add("text.apply_filters", "Apply Filters", "messages_js", "en");
t.add("text.area_based_rating", "Based on %ratingCount% rating", "messages_js", "en");
t.add("text.area_cleanliness", "Cleanliness", "messages_js", "en");
t.add("text.area_come_here", "I come here frequently", "messages_js", "en");
t.add("text.area_commuting", "Commuting", "messages_js", "en");
t.add("text.area_connectivity", "Connectivity", "messages_js", "en");
t.add("text.area_environment", "Environment", "messages_js", "en");
t.add("text.area_familiar", "How familiar are you with this area?", "messages_js", "en");
t.add("text.area_hospital", "Hospital", "messages_js", "en");
t.add("text.area_live_here", "I live here", "messages_js", "en");
t.add("text.area_market", "Market", "messages_js", "en");
t.add("text.area_neighborhood", "Neighborhood", "messages_js", "en");
t.add("text.area_neighborhood_rating", "Neighborhood Rating", "messages_js", "en");
t.add("text.area_parking", "Parking", "messages_js", "en");
t.add("text.area_place_of_interest", "Place of interest", "messages_js", "en");
t.add("text.area_public_transport", "Public Transport", "messages_js", "en");
t.add("text.area_restaurants", "Restaurants", "messages_js", "en");
t.add("text.area_roads", "Roads", "messages_js", "en");
t.add("text.area_safety", "Safety", "messages_js", "en");
t.add("text.area_schools", "Schools", "messages_js", "en");
t.add("text.area_traffic", "Traffic", "messages_js", "en");
t.add("text.area_work_here", "I work here", "messages_js", "en");
t.add("text.back", "Back", "messages_js", "en");
t.add("text.back_to_results", "Back to Search Results", "messages_js", "en");
t.add("text.bathrooms", "Bathrooms", "messages_js", "en");
t.add("text.bedrooms", "Bedrooms", "messages_js", "en");
t.add("text.building_size", "Floor Area", "messages_js", "en");
t.add("text.cancel", "Cancel", "messages_js", "en");
t.add("text.category", "Category", "messages_js", "en");
t.add("text.clear", "Clear", "messages_js", "en");
t.add("text.click_activate_map", "Click to activate map", "messages_js", "en");
t.add("text.close", "Close", "messages_js", "en");
t.add("text.contact_agent_for_price", "Contact agent for price", "messages_js", "en");
t.add("text.create_an_account", "Create an Account", "messages_js", "en");
t.add("text.create_email_search", "Create an email alert for this search.", "messages_js", "en");
t.add("text.daily", "Daily", "messages_js", "en");
t.add("text.development", "New Development", "messages_js", "en");
t.add("text.email", "Email", "messages_js", "en");
t.add("text.enter_email", "Enter your email", "messages_js", "en");
t.add("text.favorite", "Favorite", "messages_js", "en");
t.add("text.favorites", "Favorites", "messages_js", "en");
t.add("text.featured", "Featured", "messages_js", "en");
t.add("text.foreclosed", "Foreclosed", "messages_js", "en");
t.add("text.how_many_baths", "How many bathrooms do you need?", "messages_js", "en");
t.add("text.how_many_beds", "How many bedrooms do you need?", "messages_js", "en");
t.add("text.land_size", "Land Size", "messages_js", "en");
t.add("text.land_size_label", "sqm", "messages_js", "en");
t.add("text.land_size_max", "Max Sqm", "messages_js", "en");
t.add("text.land_size_min", "Min Sqm", "messages_js", "en");
t.add("text.less_filter", "Less Filter", "messages_js", "en");
t.add("text.listings_found", "Listings Found", "messages_js", "en");
t.add("text.living_size_max", "Max Sqm", "messages_js", "en");
t.add("text.living_size_min", "Min Sqm", "messages_js", "en");
t.add("text.location", "Location", "messages_js", "en");
t.add("text.login", "Login", "messages_js", "en");
t.add("text.longtail", "Keyword Suggestion", "messages_js", "en");
t.add("text.map_search_contact_property", "1 Property", "messages_js", "en");
t.add("text.more_filter", "More Filter", "messages_js", "en");
t.add("text.never", "Never", "messages_js", "en");
t.add("text.new_listing_on_your_recent_search", "New listing on your recent search", "messages_js", "en");
t.add("text.no_area_rating", "This area has no ratings yet. Be the first to rate it.", "messages_js", "en");
t.add("text.not_enough_area_rating", "This area has no ratings yet.", "messages_js", "en");
t.add("text.of", "of", "messages_js", "en");
t.add("text.offerType", "Offer Type", "messages_js", "en");
t.add("text.only", "Only", "messages_js", "en");
t.add("text.or", "or", "messages_js", "en");
t.add("text.overall_area_rating", "Overall area rating:", "messages_js", "en");
t.add("text.overall_rating", "Overall Rating", "messages_js", "en");
t.add("text.price", "Price", "messages_js", "en");
t.add("text.price_max", "Maximum", "messages_js", "en");
t.add("text.price_min", "Minimum", "messages_js", "en");
t.add("text.price_range", "Price range", "messages_js", "en");
t.add("text.property_type", "Property type", "messages_js", "en");
t.add("text.property_type_any", "Any", "messages_js", "en");
t.add("text.rate_area", "Rate this area", "messages_js", "en");
t.add("text.rating_success", "Thank you. \nYour rating was successfully submitted.", "messages_js", "en");
t.add("text.recent_search", "Your Recent Search", "messages_js", "en");
t.add("text.refine_saved_search", "Refine your search", "messages_js", "en");
t.add("text.refine_search", "Refine your search criteria to get best results", "messages_js", "en");
t.add("text.related_searches", "Related Searches", "messages_js", "en");
t.add("text.remove", "remove", "messages_js", "en");
t.add("text.save_changes", "Save Changes", "messages_js", "en");
t.add("text.saved_search", "Saved Search", "messages_js", "en");
t.add("text.search", "Search", "messages_js", "en");
t.add("text.select_amenities", "Select Amenities", "messages_js", "en");
t.add("text.set", "Set", "messages_js", "en");
t.add("text.set_email_frequency", "Set Email Frequency Alert", "messages_js", "en");
t.add("text.short_term", "Short Term", "messages_js", "en");
t.add("text.subcategories", "Subcategories", "messages_js", "en");
t.add("text.submit", "Submit", "messages_js", "en");
t.add("text.switch_list_view", "Switch to List View", "messages_js", "en");
t.add("text.switch_map_view", "Switch to Map View", "messages_js", "en");
t.add("text.to", "to", "messages_js", "en");
t.add("text.top_filter_callout", "Filter your search for better results", "messages_js", "en");
t.add("text.top_filter_callout_button", "Got it", "messages_js", "en");
t.add("text.view", "View", "messages_js", "en");
t.add("text.view_all", "View all", "messages_js", "en");
t.add("text.view_less", "View less", "messages_js", "en");
t.add("text.view_more", "View more", "messages_js", "en");
t.add("text.view_more_listings", "View more listings", "messages_js", "en");
t.add("text.weekly", "Weekly", "messages_js", "en");
t.add("text.welcome_back", "Welcome back", "messages_js", "en");
t.add("text.what_price_range", "What is your price range ?", "messages_js", "en");
t.add("text.where_to_buy", "Where do you want to buy ?", "messages_js", "en");
t.add("text.where_to_rent", "Where do you want to rent ?", "messages_js", "en");
t.add("trends.search_bar_find_city", "Find City", "messages_js", "en");
t.add("trends.search_bar_loading_areas", "Loading Locations", "messages_js", "en");
t.add("trends.search_bar_select_area", "Select Location", "messages_js", "en");
})(Translator);
